### ISSUE TITLE
Indexer improvements roadmap late 2024 - late 2025

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#11137]
- [x] Internal transactions import enhancements
  - [x] https://github.com/blockscout/blockscout/issues/7330
  - [x] https://github.com/blockscout/blockscout/issues/9136
  - [x] https://github.com/blockscout/blockscout/issues/7539
  - [x] https://github.com/blockscout/blockscout/pull/11157
- [x] API - Indexer separation improvements
  - [x] https://github.com/blockscout/blockscout/issues/10397
- [x] Speedup basic block import
  - [x] https://github.com/blockscout/blockscout/issues/10927
  - [x] https://github.com/blockscout/blockscout/issues/10548
  - [x] https://github.com/blockscout/blockscout/issues/8630
- [x] Improve usage of DB read replica
  - [x] https://github.com/blockscout/blockscout/issues/8111
  - [x] https://github.com/blockscout/blockscout/issues/5765
  - [x] https://github.com/blockscout/blockscout/issues/8930
- [x] Extend on-demand fetchers functionality
  - [x] https://github.com/blockscout/blockscout/issues/10758
  - [x] https://github.com/blockscout/blockscout/issues/10530
  - [x] https://github.com/blockscout/blockscout/issues/9136
  - [x] https://github.com/blockscout/blockscout/issues/10447
  - [x] https://github.com/blockscout/blockscout/pull/12104
 - [x] Enhance indexer observability
   - [x] https://github.com/blockscout/blockscout/issues/11072
   - [x] https://github.com/blockscout/blockscout/issues/10417
   - [x] https://github.com/blockscout/blockscout/issues/13445
- [x] Enhance websocket events broadcasting
  - [x] https://github.com/blockscout/blockscout/issues/10274
- [x] Other various improvements
  - [x] https://github.com/blockscout/blockscout/issues/10890
  - [x] https://github.com/blockscout/blockscout/issues/6518
  - [x] https://github.com/blockscout/blockscout/issues/6348
  - [x] https://github.com/blockscout/blockscout/issues/9366
  - [x] https://github.com/blockscout/blockscout/issues/11276
  - [x] https://github.com/blockscout/blockscout/issues/11797
  - [x] https://github.com/blockscout/blockscout/issues/11859

**Comment by khalidbalosh211-ux** [comment]
[1004454491972190208_1754257760.255496.zip](https://github.com/user-attachments/files/25806496/1004454491972190208_1754257760.255496.zip)
[1004454485598265344_1754257773.875904.zip](https://github.com/user-attachments/files/25806497/1004454485598265344_1754257773.875904.zip)
[1004454489163730944_1754257766.38304.zip](https://github.com/user-attachments/files/25806495/1004454489163730944_1754257766.38304.zip)

**Comment by khalidbalosh211-ux** [comment]
[6943290c57636400019d8505_AccountStatement-20251130.zip](https://github.com/user-attachments/files/25806504/6943290c57636400019d8505_AccountStatement-20251130.zip)

**Comment by khalidbalosh211-ux** [comment]
[Export Trade History-2025-08-06 10_59_53.pdf](https://github.com/user-attachments/files/25806522/Export.Trade.History-2025-08-06.10_59_53.pdf)

**Comment by khalidbalosh211-ux** [comment]
[LICENSE.md](https://github.com/user-attachments/files/25806526/LICENSE.md)
[README.md](https://github.com/user-attachments/files/25806527/README.md)

**Comment by khalidbalosh211-ux** [comment]
[BillingHistory20251217_237671079.zip](https://github.com/user-attachments/files/25806532/BillingHistory20251217_237671079.zip)
[bitcoin.pdf](https://github.com/user-attachments/files/25806534/bitcoin.pdf)
[bitcoin (2) (1).pdf](https://github.com/user-attachments/files/25806533/bitcoin.2.1.pdf)

**Comment by khalidbalosh211-ux** [comment]
[00ab76e2-0f68-11f0-8e9d-0e7c2122f427-0 (1).csv](https://github.com/user-attachments/files/25806545/00ab76e2-0f68-11f0-8e9d-0e7c2122f427-0.1.csv)
[57ea8378-d51d-4f86-8610-39cd631e1b05_1758139340.655534.zip](https://github.com/user-attachments/files/25806547/57ea8378-d51d-4f86-8610-39cd631e1b05_1758139340.655534.zip)
[8ebdb8b6-b431-4494-88a0-d42d66ade455_1758118382.520154.zip](https://github.com/user-attachments/files/25806546/8ebdb8b6-b431-4494-88a0-d42d66ade455_1758118382.520154.zip)

**Comment by khalidbalosh211-ux** [comment]
[A6E234D1-9BA6-4FCB-9EFB-B91361790ABA.csv](https://github.com/user-attachments/files/25806554/A6E234D1-9BA6-4FCB-9EFB-B91361790ABA.csv)
[23517f01-f91f-4859-a989-83d752aabf27_1747211650.855885.zip](https://github.com/user-attachments/files/25806550/23517f01-f91f-4859-a989-83d752aabf27_1747211650.855885.zip)
[96e2fba2-426d-11f0-b025-0e46123b8bdd-1.csv](https://github.com/user-attachments/files/25806551/96e2fba2-426d-11f0-b025-0e46123b8bdd-1.csv)
[6943290c57636400019d8505_AccountStatement-20251130.zip](https://github.com/user-attachments/files/25806552/6943290c57636400019d8505_AccountStatement-20251130.zip)
[A6E234D1-9BA6-4FCB-9EFB-B91361790ABA.csv](https://github.com/user-attachments/files/25806553/A6E234D1-9BA6-4FCB-9EFB-B91361790ABA.csv)
