### ISSUE TITLE
Collect and review proxy contract issues

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#8758]
- [x] Custom proxy implementation: https://blockscout.canny.io/feature-requests/p/custom-proxy-implementation (https://github.com/blockscout/blockscout/issues/8761) https://github.com/blockscout/blockscout/pull/8807

- [x] Improve detection of Gnosis safe proxy (https://github.com/blockscout/blockscout/issues/8737)

- [x] Support [EIP-1822 (UUPS proxy)](https://eips.ethereum.org/EIPS/eip-1822) https://github.com/blockscout/blockscout/pull/8807

- [x] Support [EIP-2535 Diamond proxy](https://eips.ethereum.org/EIPS/eip-2535)

- [x] Implementation is defined as 0x0000..., however EIP-1967 proxy pattern is used actually.

- [x] https://explorerl2-lyra-mainnet-0.t.conduit.xyz/address/0x6879287835A86F50f784313dBEd5E5cCC5bb8481/contracts#address-tabs should be recognized as proxy

- [x] Support Compound proxy pattern https://github.com/blockscout/blockscout/issues/8899

- [x] https://github.com/blockscout/blockscout/pull/9396

- [x] https://github.com/blockscout/blockscout/pull/9555

**Comment by ulyanas** [comment]
Not detected as proxy, no implementation 
https://eth.blockscout.com/address/0xED12310d5a37326E6506209C4838146950166760?tab=contract 

Alternative explorer shows proxied methods: https://etherscan.io/address/0xED12310d5a37326E6506209C4838146950166760#writeProxyContract
