### ISSUE TITLE
Stats Epic

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/blockscout#8961]
[Epic description](https://www.notion.so/blockscout/STAT-New-stats-and-mainpage-counters-e98b9c1640934578a170ffed5a2fb835?pvs=4)

- [ ] Add historical gas token price to the Homepage (e.g. OP for Optimism) (https://github.com/blockscout/blockscout/pull/9483)
- [ ] Add historical gas token price to the Stats > Market Data section (https://github.com/blockscout/blockscout/pull/9483)
- [ ] Add latest L1 state batch size to the Homepage (https://github.com/blockscout/blockscout/pull/9488)
- [ ] Add transactions stats to Blockchain > Transactions page: Txns 24h, Pending txns 24h, Tx fees 24h, Avg txn fee 24h (https://github.com/blockscout/blockscout/pull/9483)
- [x] Add Volume (24H) to the Token details (should be available from Coingecko) (https://github.com/blockscout/blockscout/pull/9483)
