### ISSUE TITLE
Major DB schema changes

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#9457]
Blockscout DB schema changes for the next major release:
- [ ] Eliminate `block_index` column in `internal_transactions` table: replace current composite primary key to probably [block_hash, transaction_index, index]

**Comment by k1rill-fedoseev** [comment]
Potential `logs` and `token_transfers` table optimizations:

- [ ] Drop one of `logs_block_number_ASC__index_ASC_index`, `logs_block_number_DESC__index_DESC_index` as keeping two of them is redundant. (4% of total table size)
- [ ] Drop one of `token_transfers_block_number_ASC_log_index_ASC_index`, `token_transfers_block_number_DESC_log_index_DESC_index` as keeping two of them is redundant. (4% of total table size)
- Replace `logs_pkey` with one of the following:
    - [ ] with `UNIQUE btree(block_hash, index)` (7% of total table size)
    - [ ] with `UNIQUE btree(transaction_hash, index)` AND drop `logs_transaction_hash_index_index` (20% of total table size) 
- Replace `token_transfers_pkey` with one of the following:
    - [ ] with `UNIQUE btree(block_hash, log_index)` (7% of total table size)
    - [ ] with `UNIQUE btree(transaction_hash, log_index)` AND drop `token_transfers_transaction_hash_log_index_index` (20% of total table size)

**Comment by vbaranov** [comment]
- [ ] Add B-tree index for `block_hash` column in `logs` table in order to fix https://github.com/blockscout/blockscout/issues/10491.

**Comment by vbaranov** [comment]
- [ ] Add `internal_transactions` B-tree index on on `(block_number DESC, transaction_index DESC, index DESC)` or `(block_number DESC, block_index DESC)` https://github.com/blockscout/blockscout/issues/10718#issuecomment-2443599956

**Comment by k1rill-fedoseev** [comment]
## Further proposed DB storage optimizations

Order in each table is from most obvious and trivial to least obvious and trivial.

### `internal_transactions`

- [x] Drop `internal_transactions_created_contract_address_hash_partial_ind` index (total table disk footprint is ~7%), duplicate existing values of `created_contract_address_hash` into `to_address_hash` column, replace internal tx list queries with 3 unions with just 2 unions over `from_address_hash` and `to_address_hash`. https://github.com/blockscout/blockscout/issues/12877
  1. Column `created_contract_address_hash` itself and `btree (created_contract_address_hash)` index is left unchanged since it's used for contract creation tx search.
- [x] Drop `trace_address` or compress it to a single integer, specifying relative call stack height change with respect to previous internal transaction (e.g. if previous is `[a, b, c]`, `[a, b, c, 0] -> 1, [a, b, c + 1] -> 0, [a, b + 1] -> -1, [a + 1] -> -2`) https://github.com/blockscout/blockscout/issues/12874
- [x] Replace zero values in `value` column with null (99.6% rows have 0 right now). Theory is that null occupies 1 bit, while any numeric value is at least 2 bytes. https://github.com/blockscout/blockscout/issues/12875
- [x] Replace `call_type`, `type`, `error` with enums or 1-byte strings (e.g. `staticcall -> \x00, call -> \x01, delegatecall -> \x02`). (Average disk foot print for all 3 columns right now is 15 bytes) https://github.com/blockscout/blockscout/issues/12876 https://github.com/blockscout/blockscout/issues/12880
- [x] Drop `transaction_hash` column (~6% of total table disk footprint), replace join on `transaction_hash` with join on `(block_hash, transaction_index)` or `(block_number, transaction_index)`, drop index `(transaction_hash, index)` (~10% of total table disk footprint). https://github.com/blockscout/blockscout/issues/12881

### `logs`

- [x] Compress values in 4 topic columns by trimming leading zeros. Second and third topic very often are just 20-byte addresses or small integer indices.
  1. This is backward compatible, so first iteration can be done even without backfilling migration.
- [x] Compress `data` column manually with lz4/gzip (need to benchmark performance vs compression rate), as data is almost always ABI encoded and has many zeros, offsets, etc..
  1. Probably will need new 1-byte column specifying compression algo
  2. Postgres has its own native pglz compression, but it only works for TOAST columns, and doesn't kick in if row is less than 2kb, which is typically the case for logs
- [x] Replace `transaction_hash` with `transaction_index`, replace join on `transaction_hash` with join on `(block_hash, transaction_index)`, replace primary key `(transaction_hash, block_hash, log_index)` with primary key on `(block_hash, log_index)`, drop index on `(transaction_hash, log_index)`

### `token_transfers`

- [ ] Replace `transaction_hash` with `transaction_index`, replace join on `transaction_hash` with join on `(block_hash, transaction_index)`, replace primary key `(transaction_hash, block_hash, log_index)` with primary key on `(block_hash, log_index)`, drop index on `(transaction_hash, log_index)`

### `transactions`

- [x] Drop `transactions_created_contract_address_hash_with_pending_index`, `transactions_created_from_address_hash_with_pending_index`, `transactions_created_to_address_hash_with_pending_index` as unused (as reported by pganalyze). All 3 indices have a similar index in ASC order, that's being used for list queries.
- [ ] Replace `btree (created_contract_address_hash, block_number, index, inserted_at, hash DESC)` index with `btree (created_contract_address_hash)`, duplicate existing values of `created_contract_address_hash` into `to_address_hash` column, replace tx list queries with 3 unions with just 2 unions over `from_address_hash` and `to_address_hash`.
  1. Index `btree (created_contract_address_hash)` can be used to find a creation tx (should not be more than 1 mined tx per created address, as it's deterministically derived from `from_address_hash` and `nonce`)
- [ ] Replace `btree ({from,to}_address_hash, block_number, index, inserted_at, hash DESC)` indices with `btree ({from,to}_address_hash, block_number, index)`
  1. Need to test potential space savings, but should be feasible.
- [ ] Drop `v`, `r`, `s` columns as unnecessary or at least replace them with a single 65-byte signature field (3 fields consume 88 bytes together as per pganalyze).

**Comment by fedor-ivn** [comment]
Not major, but might worth addressing:
- [ ] ~~https://github.com/blockscout/blockscout/issues/12241~~

**Comment by vbaranov** [comment]
- [x] `tokens_contract_address_hash_index` unique index duplicates `tokens_pkey` primary key in the `tokens` table. It is safe to delete unique index.

**Comment by vbaranov** [comment]
- [x] `token_instances_token_id_index` DB index on `token_instances` table is practically useless since `token_id` is always bundled with `contract_address_hash`, which is covered by PK and reverse index.
